In [341]:
import os
import pandas as pd
import sqlalchemy as sa

In [342]:
df = pd.read_csv('dummy_transactions.csv', sep = ';')
df.head()

,Tranzakció dátuma,Könyvelés dátuma,Típus,Bejövő/Kimenő,Partner neve,Partner számlaszáma/azonosítója,Költési kategória,Közlemény,Számla név,Számla szám,Összeg,Pénznem
0,2023-01-20 13:39:49,2023-01-20,Branch Cash Deposit,Income,Main Bank Telebank,NaN,Transfer,NetBank,Primary Account,1111222233334444,"40 000,0",HUF
1,2024-08-20 18:18:34,2024-08-20,ATM Withdrawal,Expense,Main Bank,NaN,Cash Withdrawal,2024-08-20 CARD-1234 Terminal Loc A,Primary Account,1111222233334444,"-4 000,0",HUF
2,2021-11-01 15:43:43,2021-11-01,Card Purchase,Expense,Corner Grocery Store,NaN,Groceries,2021-11-01 CARD-1234 Store POS Contactless,Primary Account,1111222233334444,"-340,0",HUF
3,2022-12-01 18:45:00,2022-12-01,Card Transaction Fee,Expense,Card Transaction Fee,NaN,Bills & Utilities,2022-12-01 CARD-1234 PIN Replacement Fee,Primary Account,1111222233334444,"-116,0",HUF
4,2023-07-01 18:45:00,2023-07-01,Cash Handling Fee,Expense,Cash Handling Fee,NaN,Bills & Utilities,2023-07-01 CARD-1234,Primary Account,1111222233334444,"-168,0",HUF

In [343]:
#Deleted redundant columns and switched to english names for readability
df.drop(columns=['Pénznem','Könyvelés dátuma','Bejövő/Kimenő','Számla név','Számla szám'],inplace=True)
df.columns = ['Transaction_date', 'Type', 'Partner_name', 'Partner_account', 'Spending_category', 'Description', 'Amount']

In [344]:
#Had to format for appropriate data types
df['Amount']=df['Amount'].str.replace(',','.').str.replace(' ','')
df['Amount'] = df['Amount'].astype(float)

In [345]:
df['Transaction_date'] = pd.to_datetime(df['Transaction_date'], format='%Y-%m-%d %H:%M:%S')
df.sort_values('Transaction_date',inplace=True, ignore_index=True)

In [346]:
#Switched Nulls to Unknown in case of future use in visualization
df['Partner_account'] = df['Partner_account'].fillna('Unknown')
df['Partner_account'] = df['Partner_account'].astype(str)
df.dtypes

Transaction_date     datetime64[us]
Type                            str
Partner_name                    str
Partner_account                 str
Spending_category               str
Description                     str
Amount                      float64
dtype: object

In [347]:
#Description column had some HTML spacing
df['Description'] = df['Description'].str.replace('&nbsp;' , ' ')
df.head()

,Transaction_date,Type,Partner_name,Partner_account,Spending_category,Description,Amount
0,2020-01-20 20:28:38,Card Purchase,Corner Coffee Shop,Unknown,Food & Drink,2020-01-20 CARD-1234 Corner Coffee Shop ...,-1800.0
1,2020-03-23 13:57:57,ATM Withdrawal,Main Bank,Unknown,Cash Withdrawal,2020-03-23 CARD-1234 Terminal Loc C,-5000.0
2,2020-04-08 14:44:17,Card Purchase,Convenience Store,Unknown,Other,2020-04-08 CARD-1234 Convenience Store C...,-370.0
3,2020-04-24 16:09:40,Card-to-Card Transfer,Main Bank BANK,Unknown,Not categorized,2020-04-24 CARD-1234 Online Banking ACC-9999,-600.0
4,2020-06-02 17:27:22,Card Purchase,Fresh Market,Unknown,Groceries,2020-06-02 CARD-1234 Fresh Market Cont...,-430.0

In [348]:
#Created category grouping for quick information
category_grp = df.groupby('Spending_category')
spendings = category_grp['Amount'].sum()
spendings.head()

Spending_category
Bills & Utilities     -770.0
Cash Withdrawal      -9000.0
Clothing             -2495.0
Entertainment        -2798.0
Food & Drink        -15310.0
Name: Amount, dtype: float64

In [349]:
#Extracting to SQL, if failed then extracting into .csv and .xlsxinstead
try:
    db_user=os.environ.get('db_login_name')
    db_passw=os.environ.get('db_login_passw')
    engine = sa.create_engine(f'mssql+pyodbc://{db_user}:{db_passw}@localhost\\SQLEXPRESS/finance_project?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes')
    df.to_sql('finance_table', engine, index=False , if_exists='append')
except Exception as e:
    print("Couldn't write to SQL server, exported to csv and xlsx", e)
    df.to_csv('finance_table_substitution.csv')
    df.to_excel('finance_table.xlsx')